Algoritmo "enquanto"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 2024/09/27
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva ("Números de 1 a 10")
num <- 1
enquanto (num <= 10) faca
         escreval(num)
         num <- num + 1
fimenquanto

Fimalgoritmo