Algoritmo "equilatero"
// Descrição   : Calcula o perímetro de um triângulo equilátro

Var
// Seção de Declarações das variáveis 
    lado: inteiro
    perimetro: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreva ("Introduza o valor: ")
    leia (lado)
    perimetro <- lado * 3
    escreva ("Triângulo equilátero, lado = ", lado = 13 " e perímetro = " perímetro)
    
Fimalgoritmo