Algoritmo "somatepremir0"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 2024/09/27
Var
// Seção de Declarações das variáveis 
num, soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
repita
      escreva("Digite números para serem somados: (prima 0 para sair)")
      leia(num)
      soma <- soma + num
      escreval ("Total: ", soma)
ate num = 0

Fimalgoritmo