Algoritmo "ficha5_ex5"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 2024/09/27
Var
// Seção de Declarações das variáveis 
temp: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite a temperatura em fahrenheit: ")
leia(temp)
escreva("A temperatura em celsius é ", ((temp-32)*5)/9)


Fimalgoritmo