Algoritmo "loop_2"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 2024/09/27
Var
// Seção de Declarações das variáveis 
num, i, multip: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número: ")
leia(num)
para i de 1 ate 10 passo 1 faca
     multip <- num * i
     escreval (num, " x", i, " =", multip)
fimpara

Fimalgoritmo