Algoritmo "media2num"
// Descrição   : Aqui você descreve o que o programa faz! (função)

Var
// Seção de Declarações das variáveis 
   num1: inteiro
   num2: inteiro
   media: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva ("Digite o número: ")
   leia (num1)
   escreva ("Digite um segundo número: ")
   leia (num2)
   media <- (num1 + num2) / 2
   escreva ("A média de ", num1, " com ", num2, " é ", media)

Fimalgoritmo