Algoritmo "num_seguintes"
// Descrição  :  [
Var
// Seção de Declarações das variáveis 
   num1: inteiro
   num1seg: inteiro
   num2seg: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva ("Digite um número: ")
   leia (num1)
   num1seg <- num1 + 1
   num2seg <- num1seg + 1
   escreva ("Os dois números seguintes são: ", num1seg, " e ", num2seg)

Fimalgoritmo