Algoritmo "quadrado"
// Descrição   : Aqui você descreve o que o programa faz! (função)

Var
// Seção de Declarações das variáveis 
   numero: inteiro
   quadrado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva ("Digite o número: ")
   leia (numero)
   quadrado <- numero * numero
   escreva ("O quadrado de ", numero, " é ", quadrado)

Fimalgoritmo