Algoritmo "maior_de_idade"
// Descrição   : Aqui você descreve o que o programa faz! (função)

Var
// Seção de Declarações das variáveis 
idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Introduz a sua idade:")
leia(idade)
se (idade >= 18) entao
escreval("O utilizador é maior de idade!")
senao
escreval("O utilizador é menor de idade!")
fimse

Fimalgoritmo