Algoritmo "soma2numeros"
// Descrição   : Soma de dois números inteiros

Var
// Seção de Declarações das variáveis 
   num1: inteiro
   num2: inteiro
   soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva ("Digite um número: ")
   leia (num1)
   escreva ("Digite um segundo número: ")
   leia (num2)
   soma <- num1 + num2
   escreva ("A soma de ", num1, " com ", num2, " é ", soma)

Fimalgoritmo